import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Only seed in development
  if (process.env.NODE_ENV === 'production') {
    return;
  }

  // Deletes ALL existing entries
  await knex('tasks').del();

  // Inserts seed entries
  await knex('tasks').insert([
    // E-Commerce Platform tasks
    {
      id: 1,
      project_id: 1,
      title: 'Setup project infrastructure',
      description: 'Initialize Git repository, configure CI/CD, setup development environment',
      priority: 'high',
      status: 'Completed',
      complexity: 3,
      due_date: '2025-01-10',
      estimated_hours: 16,
      assigned_to: 4,
      created_by: 3,
    },
    {
      id: 2,
      project_id: 1,
      title: 'Design database schema',
      description: 'Create ERD and design database tables for products, orders, users',
      priority: 'high',
      status: 'Completed',
      complexity: 4,
      due_date: '2025-01-15',
      estimated_hours: 20,
      assigned_to: 8,
      created_by: 3,
    },
    {
      id: 3,
      project_id: 1,
      title: 'Implement user authentication',
      description: 'JWT-based authentication with email/password and OAuth integration',
      priority: 'high',
      status: 'In Progress',
      complexity: 4,
      due_date: '2025-01-25',
      estimated_hours: 32,
      assigned_to: 4,
      created_by: 3,
    },
    {
      id: 4,
      project_id: 1,
      title: 'Create product catalog API',
      description: 'RESTful API for product management with search and filtering',
      priority: 'high',
      status: 'To Do',
      complexity: 5,
      due_date: '2025-02-05',
      estimated_hours: 40,
      assigned_to: 5,
      created_by: 3,
    },
    {
      id: 5,
      project_id: 1,
      title: 'Design UI mockups',
      description: 'Create Figma designs for homepage, product listing, and checkout',
      priority: 'medium',
      status: 'In Progress',
      complexity: 3,
      due_date: '2025-01-30',
      estimated_hours: 24,
      assigned_to: 7,
      created_by: 3,
    },
    {
      id: 6,
      project_id: 1,
      title: 'Implement shopping cart',
      description: 'Shopping cart functionality with add/remove/update operations',
      priority: 'high',
      status: 'To Do',
      complexity: 4,
      due_date: '2025-02-15',
      estimated_hours: 28,
      assigned_to: 4,
      created_by: 3,
    },
    {
      id: 7,
      project_id: 1,
      title: 'Write automated tests',
      description: 'Unit and integration tests for authentication and product APIs',
      priority: 'medium',
      status: 'To Do',
      complexity: 3,
      due_date: '2025-02-20',
      estimated_hours: 20,
      assigned_to: 6,
      created_by: 3,
    },

    // Mobile Banking App tasks
    {
      id: 8,
      project_id: 2,
      title: 'Security audit and planning',
      description: 'Review security requirements, plan encryption strategy',
      priority: 'high',
      status: 'Completed',
      complexity: 4,
      due_date: '2025-02-10',
      estimated_hours: 16,
      assigned_to: 8,
      created_by: 3,
    },
    {
      id: 9,
      project_id: 2,
      title: 'Implement biometric authentication',
      description: 'Face ID and fingerprint authentication integration',
      priority: 'high',
      status: 'In Progress',
      complexity: 5,
      due_date: '2025-03-01',
      estimated_hours: 48,
      assigned_to: 4,
      created_by: 3,
    },
    {
      id: 10,
      project_id: 2,
      title: 'Account dashboard UI',
      description: 'Design and implement user account dashboard with transaction history',
      priority: 'medium',
      status: 'To Do',
      complexity: 3,
      due_date: '2025-03-15',
      estimated_hours: 32,
      assigned_to: 4,
      created_by: 3,
    },

    // Internal HR Portal tasks
    {
      id: 11,
      project_id: 3,
      title: 'Employee database migration',
      description: 'Migrate existing employee data to new system',
      priority: 'high',
      status: 'Blocked',
      complexity: 4,
      due_date: '2025-02-01',
      estimated_hours: 24,
      assigned_to: 5,
      created_by: 2,
    },
    {
      id: 12,
      project_id: 3,
      title: 'Leave management module',
      description: 'Employee leave request and approval workflow',
      priority: 'medium',
      status: 'To Do',
      complexity: 3,
      due_date: '2025-03-01',
      estimated_hours: 30,
      assigned_to: 5,
      created_by: 2,
    },
  ]);
}

